#!/usr/bin/env bash
# Record live model responses into the committed cassettes.
#
# NOT required to reproduce any published result. `make verify` is entirely
# deterministic and offline; this script exists so the optional model-driven
# arm can be regenerated by anyone holding their own credential.
#
# Requires ANTHROPIC_API_KEY (or ANTHROPIC_AUTH_TOKEN) valid for whatever
# ANTHROPIC_BASE_URL points at. Approximate cost at time of writing: ~370
# requests, ~20 minutes, a few US dollars on a frontier model.
#
# Deliberately absent: any override of the client user agent. The client
# identifies itself honestly as `ledgergate/<version>`. If an endpoint refuses
# an honest client, that endpoint is not one this project will record against;
# see docs/PROBLEM.md, "The model arm, and why it is not the headline".
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -z "${ANTHROPIC_API_KEY:-}${ANTHROPIC_AUTH_TOKEN:-}" ]; then
  echo "no credential in the environment; set ANTHROPIC_API_KEY" >&2
  echo "nothing here is needed to reproduce the published results:" >&2
  echo "  make verify" >&2
  exit 2
fi

export LEDGERGATE_LLM_MODE=record
export PYTHONPATH=src

for corpus in holdout dev; do
  for policy in llm llm-gated; do
    echo "=== recording ${policy} on ${corpus} ==="
    python3 -m ledgergate.cli run --policy "${policy}" --corpus "${corpus}"
  done
done

echo
echo "recorded. now add the model rows to the published table:"
echo "  make headline-llm"
